In [32]:
import numpy as np
A = np.matrix([[1, 2, 1],
            [-2, 1, 1]])
B = np.matrix([[3, 1],
              [-1, 0],
              [2, 4]])
C = np.matrix([[-2, 2],
              [1, -1],
              [1, 2]])

In [39]:
#транспонирование матрицы
A = A.transpose ()
A

matrix([[ 1, -2],
        [ 2,  1],
        [ 1,  1]])

In [42]:
#задача №1
A+2*B

matrix([[7, 0],
        [0, 1],
        [5, 9]])

In [43]:
B+2*C

matrix([[-1,  5],
        [ 1, -2],
        [ 4,  8]])

In [65]:
#задача№2
#создание массива из нулей размеров 8х8
zeros_arr = np.zeros((8,8))
print (zeros_arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [69]:
#заполнение матрицы значениями в шахматном порядке
zeros_arr[1::2,::2] = 1
zeros_arr[::2,1::2] = 1
print(zeros_arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [109]:
#задача №3
V1 = np.arange(start=0, stop=1.41, step=0.1)
V1.shape =15
V1


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4])

In [110]:
V2 = np.arange(start=0, stop=6)
V2.shape =6
V2


array([0, 1, 2, 3, 4, 5])

In [152]:
#задача №4
V1 = np.arange(start=0, stop=36)
list(filter(lambda x: int(x) % 2, V1))


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35]

In [153]:
V=V1[::3]
V

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])